os: osx
before_install:
- brew install python

language: java
sudo: false
script:
- ./mvnw  gatling:execute -Dgatling.simulationClass=computerdatabase.BasicSimulation
- ./mvnw  -DnumOfUser=20  gatling:execute -Dgatling.simulationClass=jsonPlaceholder.GetExample
- ./mvnw  -DnumOfUser=20  gatling:execute -Dgatling.simulationClass=jsonPlaceholder.PostExample