#os: osx
language: java
jdk:
- oraclejdk8
sudo: false
script:
- mvn -N io.takari:maven:wrapper
- ./mvnw gatling:execute -Dgatling.simulationClass=computerdatabase.BasicSimulation
- ./mvnw -DnumOfUser=20  gatling:execute -Dgatling.simulationClass=jsonPlaceholder.GetExample
- ./mvnw -DnumOfUser=20  gatling:execute -Dgatling.simulationClass=jsonPlaceholder.PostExample
