os: osx
language: java
sudo: true
script:
- sudo ./mvnw gatling:execute -Dgatling.simulationClass=computerdatabase.BasicSimulation
- sudo ./mvnw -DnumOfUser=20  gatling:execute -Dgatling.simulationClass=jsonPlaceholder.GetExample
- sudo ./mvnw -DnumOfUser=20  gatling:execute -Dgatling.simulationClass=jsonPlaceholder.PostExample
