#os: osx
before_install:
 - chmod +x mvnw
language: java
sudo: true
script:
- ./mvnw clean
- ./mvnw gatling:execute -Dgatling.simulationClass=computerdatabase.BasicSimulation
- ./mvnw -DnumOfUser=20  gatling:execute -Dgatling.simulationClass=jsonPlaceholder.GetExample
- ./mvnw -DnumOfUser=20  gatling:execute -Dgatling.simulationClass=jsonPlaceholder.PostExample
