os: osx
before_install:
- brew install maven

language: java
sudo: false
script:
- mvn gatling:execute -Dgatling.simulationClass=computerdatabase.BasicSimulation
- mvn -DnumOfUser=20  gatling:execute -Dgatling.simulationClass=jsonPlaceholder.GetExample
- mvn -DnumOfUser=20  gatling:execute -Dgatling.simulationClass=jsonPlaceholder.PostExample
